name: Run Frontend ci
on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn install
      - name: Build frontend
        run: yarn run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn install
      - name: Build frontend
        run: yarn run lint
